
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxtuychhivqfhbdfcuie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4dHV5Y2hoaXZxZmhiZGZjdWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjU0NTEsImV4cCI6MjA2MDEwMTQ1MX0.EwONHwcEzYzrQAc1PjLSIN9qRyC70BrnS0MAhuWouZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storage: localStorage,
    autoRefreshToken: true,
  }
});
